{% set name = "coreutils" %}
{% set version = "9.5" %}
{% set sha256 = "cd328edeac92f6a665de9f323c93b712af1858bc2e0d88f3f7100469470a1b8a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name  }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - libtool
  host:
    - libiconv  # [osx]

test:
  commands:
    - ln --relative --help 
    - wc --version
    - cat --version

about:
  home: https://www.gnu.org/software/coreutils
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'The GNU Core Utilities are the basic file, shell and text manipulation utilities of the GNU operating system.'

  doc_url: https://www.gnu.org/software/coreutils/manual/html_node/index.html
  dev_url: http://git.savannah.gnu.org/cgit/coreutils.git

extra:
  recipe-maintainers:
    - sodre
    - mbargull
