travis:
  secure:
    BINSTAR_TOKEN: SHNZUhW4rtTDW/61f3+fgypJpGRXjXLfJoW6OzzJxHb0YRPRDZkQUKyulgHC8sZZ0iUnJQtSK1zbVxSgc9TCptxwkKK3WaXuzAVnRUXPCbxBRzfd8SIQIwt3SlvGMkdM2oQWlvK+bIy7Laqk5pBmyFRM+zPmecOZ2cS81B8ZDltNcvzojNjnThG3LL2QMd+C/85fJsZ59TlV4iXq9hi23enll8uehJx7wfe/YcEuWuGU6A/4SRhnEgfhaSOnC+SFxDca9QYhJ3tP8Y6iSq3NrYntUNAASR8MsKnIUoc7RU1eKuSDllTXuWDapuvkYll4D4HUaqQiTxSYMGspHuDsR2cCwgrL/qKli6mZ1x64cFdoFZQgSv687cgKNTWSPm2BCta14nz1NfGQU/NryqWbqM0m8KvVo7jtq6Wgc52+oADzb41Hjdg66W0iuNOGnQMGsRWWCZ7XXEUeBg3GVuEfil2kOCXgSsf7JUUmtuANNPLhUMRdFF5Wl0eBr/YHsVqEG5FW+AQ1WeK7dPju5koTTgLlluqummGoQZm8E/CbdgkFd6xBBkOMrljOfz66fHyKLxs8jYa+DLsmjmx9VeKsm6BmLYgo7haVq80R8NV+SxPDdLWdpE7fshDfezRZpCKU6b1ivfpmvPmyF0myn/tDQJpbsh+p4w3WBIcyvffYiYY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
